### ISSUE TITLE
Commit 8937d88 reverted changes from "Certificates and services monitoring #102"

### ISSUE THREAD

**Issue by postilion** [rbicelli/pfsense-zabbix-template#137]
#102  added useful features, including certificate monitoring, and a simple way (via macros) to enable/disable the monitoring of specific services.  This was reverted in 8937d88.  Since that commit occurred prior to template conversion from v5 to v6 (xml to yaml) the new v6 templates are also missing these enhancements.

Was this intentional?  Sure would be nice to have these features back.  We're not using the cert monitoring, but can see the value of it.  The active service control is a must-have for us.  For example, we have disabled dhsbl on most of our firewalls, and it'd be nice to have a simple, macro-driven, way to disable this.

Thanks,
-nic

**Comment by rbicelli** [comment]
it wasn't intentional, but since certificate checking was ported, I don't see the point of use a macro for disabling a trigger for a service when you could disable the trigger from Zabbix UI. That's what most of us do: disable triggers that doesn't matter.

If you need that feature however I can port back it.
