### ISSUE TITLE
Latest data not populating

### ISSUE THREAD

**Issue by marcos-zabbiz-ta** [rbicelli/pfsense-zabbix-template#173]
Hello! 

Thank you for all of these scripts. My issue is that only few data points are showing up.

Agent Script Version
DHCP Failover Pool Problems
Expected CARP Status
SMART Status

Everything else is NOT populating. I verify the PHP on the firewall and everything is there.

Thank you for your help.

Zabbix 6.0.1

23.05.1-RELEASE (arm)
built on Wed Jun 28 03:58:46 UTC 2023
FreeBSD 14.0-CURRENT

A

**Comment by GuillaumeHullin** [comment]
What error are you getting in your Latest Data with **Show details** enabled?

**Comment by antun3s** [comment]
I am having this problem on two of my pfSense firewalls.
I haven't been able to identify the cause yet. 

Can you please run this command to check if the problem is the same:
`/usr/local/bin/php /root/scripts/pfsense_zbx.php dhcp failover`

My result is:
![Captura de tela de 2024-05-22 11-10-21](https://github.com/rbicelli/pfsense-zabbix-template/assets/6098562/3f71b2e8-28d9-424e-80d7-27c114eda229)

**Comment by GuillaumeHullin** [comment]
Are you sure you are running the latest `pfsense_zbx.php`?
Testing on my side doesn't return any error.

**Comment by antun3s** [comment]
It works.
Thanks @GuillaumeHullin

**Comment by marcos-zabbiz-ta** [comment]
I don't get any error.

I verify the PHP version and its PHP 8.2.4 (cli).

I run the command above and I get 0 as the output.

**Comment by GuillaumeHullin** [comment]
Ok and from Zabbix side, do you see errors in Latest Data?
