### ISSUE TITLE
After update 2.7.2, the upload, download and information values ​​have an error: Value of type "string" is not suitable for value type "Numeric (unsigned)". Value ""

### ISSUE THREAD

**Issue by cris710s** [rbicelli/pfsense-zabbix-template#179]
Hello friend
I've been using pfsense active with zabbix 6 for about a few days, and speed test, everything was working, except download and upload information from my second WAN link, I decided to update pfsense to 2.7.2, however several items found with this message:
The value of type "string" is not suitable for the value type "Numeric (unsigned)". Value ""

How can I proceed?

Testing speedtest directly in ssh I got everything back ok.
![Uploading Captura de tela 2024-07-07 215003.png…]()

**Comment by cris710s** [comment]
I was on version 2.6.0, and updated to 2.7.0 and later 2.7.2.
I have no knowledge of the scripts to be able to change, I found it strange to give these errors, since in your post it was validated precisely in this scenario: Zabbix 6 + pfsense 2.7.2. I believe I have sinned in some item.

**Comment by da99Beast** [comment]
I have seen this error when the script is not running or a dependency is not present - so the script result is text and not the expected value type - Numeric (unsigned) here.

I would validate that all scripts are in place and the Zabbix agent config is setup correctly on your upgraded pfSense.

**Comment by cris710s** [comment]
Could you tell me how I can see if the script is in effect? What if there is an error?

**Comment by cris710s** [comment]
No zabbix server logs were able to identify the same scenario for OpenVPN

**Comment by cris710s** [comment]
![Uploading Captura de tela 2024-07-08 130456.png…]()

**Comment by cris710s** [comment]
113225:20240708:145600.987 item "pfsenseibiuna:pfsense.value[openvpn_server_uservalue,3+philip.lisboa,bytes_recv]" became not supported: Value of type "string" is not suitable for value type "Numeric (unsigned)". Value ""
113224:20240708:145602.030 item "pfsenseibiuna:pfsense.value[openvpn_server_uservalue,3+philip.lisboa,bytes_sent]" became not supported: Value of type "string" is not suitable for value type "Numeric (unsigned)". Value ""
113222:20240708:145604.239 item "pfsenseibiuna:pfsense.value[openvpn_server_uservalue,3+philip.lisboa,connect_time_unix]" became not supported: Value of type "string" is not suitable for value type "Numeric (unsigned)". Value ""
113218:20240708:152359.668 executing housekeeper

**Comment by da99Beast** [comment]
Look at the install again - repeat the process.  Chances are, your upgrade of pfSense removed part of the install.

https://github.com/rbicelli/pfsense-zabbix-template#configuration

The Zabbix template is looking for a number but the pfSense firewall is returning a text value - if something is missing (script, speedtest binaries, etc) the output from zabbix user parameters may return something like "Command not found." instead of a numerical value as expected.

This is to get your setup working again - I can't help the dual wan speedtest issue as I only have 1 wan and no way to test.  Someone else will have to assist on this issue, if able.
