### ISSUE TITLE
Escape @ at openvpn_server_uservalue

### ISSUE THREAD

**Issue by dragoangel** [rbicelli/pfsense-zabbix-template#58]
In zabbix agent logs:
18062:20201221:132549.756 active check "pfsense.value[openvpn_server_uservalue,3+user@domain,virtual_addr]" is not supported: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.

**Comment by rbicelli** [comment]
Need special char replacement back and forth.

**Comment by rbicelli** [comment]
Closed with latest commit

**Comment by dragoangel** [comment]
Thank you, fix is working 😃

**Comment by dragoangel** [comment]
Also can I ask you about Gateway INTERFACE Status? I always have it as Down (5), think after some update. In pfSense I have all GWs as Up and running, how to debug why I have incorrect value?

**Comment by rbicelli** [comment]
What is "Gateway Status Raw" item saying?

**Comment by dragoangel** [comment]
`WAN01GW.online,WAN01HE_TUNNELV6.online,WAN02GW.online,WAN02HE_TUNNELV6.online`

When it was working it was:
`WAN01GW.none,WAN01HE_TUNNELV6.none,WAN02GW.none,WAN02HE_TUNNELV6.none`

**Comment by rbicelli** [comment]
Are you using a development/upcoming version of pfsense? I'm asking this
because when I work on template I use the pfsense sources on github as
reference, and I noticed when developing a dhcp failover check source on my
pfsense box are different than sources on repo.
In this case the fix is simple, will update asap.

Il Lun 18 Gen 2021, 20:33 Dmitriy Alekseev <notifications@github.com> ha
scritto:

**Comment by dragoangel** [comment]
Sorry, edited my reply, on one gw - yes ut is 2.5 devel and on second is 2.4.5_p1
