### ISSUE TITLE
pfSense Gateway status Changed then resolved in 1-3 minutes

### ISSUE THREAD

**Issue by Emilyen777** [rbicelli/pfsense-zabbix-template#89]
Hi @rbicelli 

I have installed the latest templates but I keep getting false errors. There are such errors on the pfsense box:
/root/scripts/pfsense_zbx.php: dpinger: timeout while retrieving status for gateway

![image](https://user-images.githubusercontent.com/92591624/140393849-e801a9fd-ab04-445c-b54d-50adbe993d96.png)

Appreciate any help!

Thanks a lot

**Comment by rbicelli** [comment]
Hi! Have you increased the timeout on zabbix agent? Take a look on readme file!

**Comment by Emilyen777** [comment]
Hey Riccardo,

Thank you for your fast reply. Yes Timeout=10

**Comment by GuillaumeHullin** [comment]
Hi @Emilyen777, could it be that your connection have packet loss enough for pfSense to actually put your gateway down temporarily ? If you only have one gateway then I advise you to check the box "Disable Gateway Monitoring Action" in your gateway settings. 
I also use a Packet Loss thresholds of 30/60 instead of 10/20.

**Comment by rbicelli** [comment]
Try also to set a different monitor IP (usually the next hop of your gateway).

**Comment by Emilyen777** [comment]
> Hi @Emilyen777, could it be that your connection have packet loss enough for pfSense to actually put your gateway down temporarily ? If you only have one gateway then I advise you to check the box "Disable Gateway Monitoring Action" in your gateway settings. I also use a Packet Loss thresholds of 30/60 instead of 10/20.

Hi @GuillaumeHullin , 

Thanks for your reply. I have checked in Status-Monitoring-Quality Graphs of my Gateway and did not find any packet loss or critical delays. The point is - I do want monitor "not fake" changes of my gateway.

**Comment by Emilyen777** [comment]
> Try also to set a different monitor IP (usually the next hop of your gateway).

Hi @rbicelli 
I have tried to Monitor IP with 8.8.8.8,1.1.1.1,1.0.0.1 - ditto(

**Comment by GuillaumeHullin** [comment]
If 8.8.8.8,1.1.1.1,1.0.0.1 are used in some DNS configuration of pfSense then I think you might have trouble because pfSense add a static route to the monitoring IP.

(https://docs.netgate.com/pfsense/en/latest/routing/gateway-configure.html section **Monitoring IP**)

You can try using OpenDNS servers 208.67.220.220 (that's what I use)

Concerning monitoring changes on the gateway, I fully understand and I was just mentioning it as a sidenote. I did encountered some problem where pfSense was shutting down the one and only gateway because of high packet loss... instead of letting the traffic through (slow is better than nothing). You gonna anyway receive an alert in Zabbix for packet loss.  So when I'm in only 1 WAN configuration then I check "Disable Gateway Monitoring Action".

**Comment by rbicelli** [comment]
Which pfSense version are you using?

**Comment by Emilyen777** [comment]
> Which pfSense version are you using?

pfSense community edition on VMware Virtual Machine, 2.5.2-Release

**Comment by rbicelli** [comment]
I'm closing this issue since is definetly a non-template related issue but a pfsense configuration issue.
