### ISSUE TITLE
Issue: Zabbix 4.4.10 and pfSense 21.05-RELEASE

### ISSUE THREAD

**Issue by gautamparthasarathy** [rbicelli/pfsense-zabbix-template#95]
Followed all directions in the readme.md but still having issue importing the ipsec template into Zabbix:

Invalid tag "/zabbix_export/version": unsupported version number.

Please help! I have a POC running that is supposed to have me monitoring IPSec tunnels from pfSense via Zabbix. 

Thank you!

**Comment by rbicelli** [comment]
Hello,
are you trying to import templates in zabbix4 folder? If yes and it isn't working I can't provide support since I don't ave any Zabbix 4 installations. Zabbix 4.0 LTS went out of support on october 31. I thing Zabbix 4.4 went out of support on jan 2020.

I'm developing the template on current LTS version and I suggest you to migrate your installation to the current available LTS (5.0), if you can.
